US22, US24 Criar Tela de Edicao de Perfil
fga-eps-mds/2020.2-Anunbis-Frontend pull request #14
Opened 2021-04-14 01:11 UTC by mangabeiras

Eu, como aluno, desejo ver e editar os dados da minha conta. Pensando nisso, esse pull request cria a tela de edição de perfil das contas dos alunos. Dados como nome, matricula e curso estão presentes nessa tela. Também foi adicionado a função de sair da conta para os alunos.

De quebra, alguns detalhes foram adicionados. Como por exemplo, quando a tela de login esta se comunicando com o backend, o ponteiro do mouse fica em modo de carregamento, para simular a conexão.

Vale lembrar que esse pull request consta somente com a parte principal do frontend. Quando haver finalização e integração com back end, com alguns ajustes, tudo funcionará perfeitamente. 

## Descrição 

Primeiramente foi criado a view 'Profile'. Depois foi criado o botao que engloba 'Configurar', 'Sobre' e 'Sair'. Após, a view de Profile foi configurada para apresentar os dados do estudante logado, juntamente com apresentação de mudar senha e excluir conta. Por fim, o detalhe da alteração do ponteiro do mouse na view de Login foi alterado.

## Resolve (Issues)

Resolve o frontend das seguintes issues:
[#140](https://github.com/fga-eps-mds/2020.2-Anunbis/issues/140) 
[#142](https://github.com/fga-eps-mds/2020.2-Anunbis/issues/142)

## Como Isso Foi Testado (caso necessário)?

Foi testado com utlização do docker, npm e inspecionar do navegador

## Capturas de Tela (se apropriado):

![image](https://user-images.githubusercontent.com/54643519/114638700-a2821080-9ca2-11eb-9cd6-b37dd03a5bc7.png)
![image](https://user-images.githubusercontent.com/54643519/114638484-153ebc00-9ca2-11eb-90cc-266bc921ca92.png)
![image](https://user-images.githubusercontent.com/54643519/114638655-8b432300-9ca2-11eb-98ae-715b00abf386.png)

## Tarefas gerais realizadas

* Criar a view de Profile;
* Criar o component MenuOption(primeira imagem do pull);
* Criar o component ResetPassword;
* Integrar a view Profile com os dois components criados;
* Adição, na página view, da alteração do mouse ao comunicar com backend

2021-04-14 17:23 UTC, oEduardoAfonso requested changes
Testei as funcionalidades e tudo parece funcionar muito bem, só a questão do nome do arquivo que foi alterado e gerou erros na renderização, mas fazendo a devida mudança funciona perfeitamente.

2021-04-14 17:23 UTC, oEduardoAfonso commented on src/components/Menu/index.js
> +import {logOut} from '../../services/authentication'
O nome do arquivo "authentication" mudou para "Auth", então quebrou nessa parte

2021-04-14 17:23 UTC, oEduardoAfonso commented on src/views/Profile/index.js
> +import { logOut } from '../../services/authentication'
Mesma coisa aqui

2021-04-14 22:29 UTC, mangabeiras commented on src/views/Profile/index.js
> +import { logOut } from '../../services/authentication'
Certo Eduardo! Consertei esses problemas. Obrigado por observá-los

2021-04-15 01:27 UTC, oEduardoAfonso approved these changes
Agora sim tudo certo!! :clap: :clap: :clap:

2021-04-15 01:45 UTC, victorhugo21 reviewed
Testei e não encontrei nenhum erro, bom trabalho Roberto!

2021-04-15 01:45 UTC, victorhugo21 approved these changes

2021-04-15 15:12 UTC, RcleydsonR approved these changes
Testei juntamente ao back para aproveitar de todas funcionalidades e parece estar tudo correto, a única coisa que não gostei (que não é culpa sua kkk) é essa arquitetura do front, tá tudo meio que mal encapsulado, mas enfim, vamos trabalhar nessa mudança ! Excelente trabalho Roberto, você é demais !

2021-04-15 15:12 UTC, merged