#180 Melhorar Pesquisa Professor
fga-eps-mds/2020.2-Anunbis-Frontend pull request #18
Opened 2021-04-28 22:38 UTC by thiagohdaqw

## Descrição 

Tentei dar uma melhorada na pagina de pesquisa do professor. Para a primeira experiencia com React no projeto, acho que ficou aceitavel.

## Resolve (Issues)

[#180](https://github.com/fga-eps-mds/2020.2-Anunbis/issues/180)

## Capturas de Tela (se apropriado):

https://user-images.githubusercontent.com/54081877/116480717-3e417e00-a858-11eb-8f51-772605b343c6.mp4

## Tarefas gerais realizadas

* Animações adicionadas
* Adição do painel lateral com os professores encontrados
* Painel central com apenas avaliações
* Adicao de informacoes no painel central
* Criação de componente de PopUp

2021-04-28 22:39 UTC, thiagohdaqw commented
# Popup
https://user-images.githubusercontent.com/54081877/116283894-d6f5d200-a762-11eb-88cd-7439cfadcc70.mp4

2021-04-29 00:04 UTC, victorhugo21 requested changes
Tá com um bugzinho nos likes, quando vc clica em um botão e vai pra outra materia ou professor ele desclica e só atualiza quando dá f5, acho que seja porque quando vc clica em algum botão seja de concordo ou discordo, ele manda pro back, porem quando vc sai dessa tela e volta ainda tá pegando os dados da primeira requisição. Mas fora isso, tá mto bom, os códigos sempre bem organizados e limpos. Quando eu crescer quero ser que nem tu kkkkkkk

2021-04-29 00:10 UTC, thiagohdaqw commented
Vish, pra arrumar esse bug ai, vai ter q mudar a logica de acesso ao backend, pois, na situação atual, ele só é chamado quando entra na pagina e retorna todos os professores encontrados com seus posts. Entao, para que os posts apareçam atualizados quando trocar o professor, tem que pedir pro backend os posts desse professor na hora que clicar pra trocar.

2021-04-29 00:14 UTC, thiagohdaqw commented
Tava vendo aqui um exemplo no site da [kabum](https://www.kabum.com.br/cgi-local/site/listagem/listagem.cgi?string=placa&btnG=&pagina=1&ordem=6&limite=50&prime=false&marcas=[%2233%22,%222767%22]&tipo_produto=[]&filtro=[]) e, quando muda algum parametro de filtro, a pagina recarrega. Então, talvez seja mais adequado fazer essa busca nova no backend mesmo.

2021-04-29 04:03 UTC, thiagohdaqw commented
Acho que corrigi o que foi citado acima. Além disso, criei um novo componente de loading tbm.

https://user-images.githubusercontent.com/54081877/116501223-a909ae00-a886-11eb-9fa8-6bded48bdd18.mp4

2021-04-29 04:06 UTC, victorhugo21 approved these changes
Acompanhei a resolução do problema via pareamento e foi solucionado! Tivemos que adicionar uma rota no backend pra fazer as requisições com os dados que a gente precisava em cada componente, agora quando o usuário escolher outro professor ou disciplina ele faz a requisição para vir somente os posts do professor em questão, assim, o componente sempre será atualizado. Muito bom trabalho Thiago!

2021-04-29 20:40 UTC, mangabeiras approved these changes
Testado com branch #180 do back. Funcionou tudo perfeitamente. Muito bom, agora nossa pesquisa de professor tem nova cara :)

2021-04-29 20:41 UTC, merged